bf: beware of failing distcheck
* buildfarm/check: here.

diff --git a/buildfarm/check b/buildfarm/check
--- a/buildfarm/check
+++ b/buildfarm/check
@@ -3,14 +3,26 @@
 set -e
 . $(dirname "$0")/common
 
-make_()
-{
-  make DESTDIR="$DIR_INSTALL" "$@"
-}
-
 check()
 {
-  make check -j${NBPROC:-2} "$@"
+  if make  -j${NBPROC:-2} check "$@"; then
+    :
+  else
+    sta=$?
+    # If distcheck was run and failed in its course, it probably
+    # left readonly directories that Teamcity will fail to clean.
+    #
+    for distdir in vaucanson-*
+    do
+      if test -d "$distdir"; then
+        # Taken from Automake's am__remove_distdir.
+        find "$distdir" -type d ! -perm -200 -exec chmod u+w {} ';' \
+            && rm -rf "$distdir" \
+            || { sleep 5 && rm -rf "$distdir"; };
+      fi
+    done
+    exit $sta
+  fi
 }
 
 ## ------ ##
