maint: bf: build out of tree
* buildfarm/common (DIR_ROOT): New.
(DIR_BUILD): Be different from DIR_SOURCE.
* buildfarm/bootstrap: Rebootstrap only when needed.

diff --git a/buildfarm/configure b/buildfarm/configure
--- a/buildfarm/configure
+++ b/buildfarm/configure
@@ -14,6 +14,12 @@ CONFIGUREFLAGS="                                \
   CXX='ccache g++-4.8'"
 
 if $(older "$DIR_BUILD/Makefile" "$0"); then
+  if test ! -d "$DIR_BUILD"; then
+    test ! -e "$DIR_BUILD" \
+      || fatal "DIR_BUILD is not a directory: $DIR_BUILD"
+    mkdir "$DIR_BUILD" \
+      || fatal "cannot mkdir $DIR_BUILD"
+  fi
   cd "$DIR_BUILD"
   run "$DIR_SOURCE/configure"                   \
     --config-cache                              \
