bf: handle the distcheck failure at the right place
* buildfarm/check: Move it from here...
* buildfarm/package: to there.

diff --git a/buildfarm/package b/buildfarm/package
--- a/buildfarm/package
+++ b/buildfarm/package
@@ -4,4 +4,25 @@ set -e
 . $(dirname "$0")/common
 
 cd "$DIR_BUILD"
-make distcheck -j${NBPROC:-2} DISTCHECK_CONFIGURE_FLAGS='CXX="$(CXX)"'
+
+distcheck()
+{
+  if make -j${NBPROC:-2} distcheck "$@"; then
+    :
+  else
+    sta=$?
+    # If distcheck was run and failed in its course, it probably
+    # left readonly directories that Teamcity will fail to clean.
+    #
+    for distdir in vaucanson-*
+    do
+      if test -d "$distdir"; then
+        # Taken from Automake's am__remove_distdir.
+        find "$distdir" -type d ! -perm -200 -exec chmod u+w {} ';'
+      fi
+    done
+    exit $sta
+  fi
+}
+
+distcheck DISTCHECK_CONFIGURE_FLAGS='CXX="$(CXX)"'
