fsm: start improving the FSM output
There are several issues with the current FSM output: it does not
support labels, weights, handles improperly the special symbol (used
for initial and final transitions) and the difference between acceptor
and transducer.  It is not clear that OpenFST makes a real difference
between transducers and acceptors though.

* tests/checker (check): Support the "ignore" option.
* tests/tafkit/fsm.chk: New.
* tests/tafkit/local.mk: Adjust.
* vcsn/algos/fsm.hh: Be sure to map the special symbol and the one
symbol to 0.
Remove spurious EOL at the end.

diff --git a/tests/checker b/tests/checker
--- a/tests/checker
+++ b/tests/checker
@@ -164,6 +164,8 @@ rst_expect ()
 # - 'stdout', then don't check the output, but leave it in the file
 #   named "stdout".
 #
+# - 'ignore', then don't check, nor report, the output.
+#
 # $builddir will prepended to PROG, unless PROG is '-PROG'.
 run ()
 {
@@ -223,15 +225,22 @@ EOF
 
     # Stdout.
     case $out_exp in
-      (stdout)
-      # Produce nice logs (with the following rst_expect).
-      cp out.eff out.exp
-      # Prepare stdout.
-      cp out.eff stdout
-      ;;
+      (ignore)
+        rst_pre "Standard error" err.eff || fail=true
+        ;;
+      (*)
+        case $out_exp in
+          (stdout)
+          # Produce nice logs (with the following rst_expect).
+          cp out.eff out.exp
+          # Prepare stdout.
+          cp out.eff stdout
+          ;;
+        esac
+        rst_pre "Standard error" err.eff || fail=true
+        rst_expect out || fail=true
+        ;;
     esac
-    rst_pre "Standard error" err.eff || fail=true
-    rst_expect out || fail=true
   } >stdout.tmp
   if $fail; then
     fail="FAIL: "
